### ISSUE TITLE
what is hash.end() do ?

### ISSUE THREAD

**Issue by nshen** [PacktPublishing/Practical-Cryptography-in-Node.js#1]
Hi @ItalyPaleAle  There is a Error if I add `hash.end()`,  I found there is no `hash.end()` in the book,  is this a typo? should I remove this line?

https://github.com/PacktPublishing/Essential-Cryptography-for-JavaScript-Developers/blob/660a8909df6ce02d7520de0da53dd91897977093/ch3-hashing/sha2-stream.js#L22

**Comment by ItalyPaleAle** [comment]
Hi @nshen thanks for the issue!

Good catch that `.end` is missing in the book. I believe calling `.end()` is optional:

- `.end` is a method for the stream that indicates that no more data will be written. This is part of the Node.js Stream APIs, not crypto (in Node.js `crypto.Hash` implements the Stream APIs)
- `.digest` causes the hash to be computed, and that's a crypto method.
- It's perfectly fine to compute a SHA-2 hash on certain data, and then add more data and re-compute the hash.
   - Essentially, if you call `.end` you tell the Node.js stream that there won't be more data
   - If you don't, the stream can still be written to
   - In any case, computing the hash is still ok!

**Comment by nshen** [comment]
Hi @ItalyPaleAle thanks for your reply.  But if I leave `.end()` there, it will throw an Error.  I have to remove it to make it work. Maybe it's not an optional ?

<img width="777" alt="image" src="https://github.com/PacktPublishing/Essential-Cryptography-for-JavaScript-Developers/assets/181506/52323f16-f493-4eed-9bc7-19d68eecad35">

**Comment by ItalyPaleAle** [comment]
What version of Node.js are you using? I tried on 19 and it works.

**Comment by nshen** [comment]
Oh thanks. It's the problem of bun.sh , node.js works fine.

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!
